<?php

namespace ContainerLCVAimD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_19BfYL3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.19BfYL3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.19BfYL3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BoardController::delete' => ['privates', '.service_locator.YFu3bo.', 'get_ServiceLocator_YFu3bo_Service', true],
            'App\\Controller\\BoardController::edit' => ['privates', '.service_locator.YFu3bo.', 'get_ServiceLocator_YFu3bo_Service', true],
            'App\\Controller\\BoardController::index' => ['privates', '.service_locator.b3GIiAo', 'get_ServiceLocator_B3GIiAoService', true],
            'App\\Controller\\BoardController::new' => ['privates', '.service_locator.b3GIiAo', 'get_ServiceLocator_B3GIiAoService', true],
            'App\\Controller\\BoardController::show' => ['privates', '.service_locator.FFEicsH', 'get_ServiceLocator_FFEicsHService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\TaskController::delete' => ['privates', '.service_locator.tOGM8VG', 'get_ServiceLocator_TOGM8VGService', true],
            'App\\Controller\\TaskController::edit' => ['privates', '.service_locator.tOGM8VG', 'get_ServiceLocator_TOGM8VGService', true],
            'App\\Controller\\TaskController::index' => ['privates', '.service_locator.9_KHQ37', 'get_ServiceLocator_9KHQ37Service', true],
            'App\\Controller\\TaskController::new' => ['privates', '.service_locator.9_KHQ37', 'get_ServiceLocator_9KHQ37Service', true],
            'App\\Controller\\TaskController::show' => ['privates', '.service_locator.ATFD0HV', 'get_ServiceLocator_ATFD0HVService', true],
            'App\\Controller\\TaskListController::delete' => ['privates', '.service_locator.Yc9l2iG', 'get_ServiceLocator_Yc9l2iGService', true],
            'App\\Controller\\TaskListController::edit' => ['privates', '.service_locator.Yc9l2iG', 'get_ServiceLocator_Yc9l2iGService', true],
            'App\\Controller\\TaskListController::index' => ['privates', '.service_locator.hVyfUoj', 'get_ServiceLocator_HVyfUojService', true],
            'App\\Controller\\TaskListController::new' => ['privates', '.service_locator.hVyfUoj', 'get_ServiceLocator_HVyfUojService', true],
            'App\\Controller\\TaskListController::show' => ['privates', '.service_locator.lUKs57B', 'get_ServiceLocator_LUKs57BService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\BoardController:delete' => ['privates', '.service_locator.YFu3bo.', 'get_ServiceLocator_YFu3bo_Service', true],
            'App\\Controller\\BoardController:edit' => ['privates', '.service_locator.YFu3bo.', 'get_ServiceLocator_YFu3bo_Service', true],
            'App\\Controller\\BoardController:index' => ['privates', '.service_locator.b3GIiAo', 'get_ServiceLocator_B3GIiAoService', true],
            'App\\Controller\\BoardController:new' => ['privates', '.service_locator.b3GIiAo', 'get_ServiceLocator_B3GIiAoService', true],
            'App\\Controller\\BoardController:show' => ['privates', '.service_locator.FFEicsH', 'get_ServiceLocator_FFEicsHService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\TaskController:delete' => ['privates', '.service_locator.tOGM8VG', 'get_ServiceLocator_TOGM8VGService', true],
            'App\\Controller\\TaskController:edit' => ['privates', '.service_locator.tOGM8VG', 'get_ServiceLocator_TOGM8VGService', true],
            'App\\Controller\\TaskController:index' => ['privates', '.service_locator.9_KHQ37', 'get_ServiceLocator_9KHQ37Service', true],
            'App\\Controller\\TaskController:new' => ['privates', '.service_locator.9_KHQ37', 'get_ServiceLocator_9KHQ37Service', true],
            'App\\Controller\\TaskController:show' => ['privates', '.service_locator.ATFD0HV', 'get_ServiceLocator_ATFD0HVService', true],
            'App\\Controller\\TaskListController:delete' => ['privates', '.service_locator.Yc9l2iG', 'get_ServiceLocator_Yc9l2iGService', true],
            'App\\Controller\\TaskListController:edit' => ['privates', '.service_locator.Yc9l2iG', 'get_ServiceLocator_Yc9l2iGService', true],
            'App\\Controller\\TaskListController:index' => ['privates', '.service_locator.hVyfUoj', 'get_ServiceLocator_HVyfUojService', true],
            'App\\Controller\\TaskListController:new' => ['privates', '.service_locator.hVyfUoj', 'get_ServiceLocator_HVyfUojService', true],
            'App\\Controller\\TaskListController:show' => ['privates', '.service_locator.lUKs57B', 'get_ServiceLocator_LUKs57BService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\BoardController::delete' => '?',
            'App\\Controller\\BoardController::edit' => '?',
            'App\\Controller\\BoardController::index' => '?',
            'App\\Controller\\BoardController::new' => '?',
            'App\\Controller\\BoardController::show' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\TaskController::delete' => '?',
            'App\\Controller\\TaskController::edit' => '?',
            'App\\Controller\\TaskController::index' => '?',
            'App\\Controller\\TaskController::new' => '?',
            'App\\Controller\\TaskController::show' => '?',
            'App\\Controller\\TaskListController::delete' => '?',
            'App\\Controller\\TaskListController::edit' => '?',
            'App\\Controller\\TaskListController::index' => '?',
            'App\\Controller\\TaskListController::new' => '?',
            'App\\Controller\\TaskListController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BoardController:delete' => '?',
            'App\\Controller\\BoardController:edit' => '?',
            'App\\Controller\\BoardController:index' => '?',
            'App\\Controller\\BoardController:new' => '?',
            'App\\Controller\\BoardController:show' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\TaskController:delete' => '?',
            'App\\Controller\\TaskController:edit' => '?',
            'App\\Controller\\TaskController:index' => '?',
            'App\\Controller\\TaskController:new' => '?',
            'App\\Controller\\TaskController:show' => '?',
            'App\\Controller\\TaskListController:delete' => '?',
            'App\\Controller\\TaskListController:edit' => '?',
            'App\\Controller\\TaskListController:index' => '?',
            'App\\Controller\\TaskListController:new' => '?',
            'App\\Controller\\TaskListController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
