<?php

namespace ContainerLCVAimD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FFEicsHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FFEicsH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FFEicsH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'board' => ['privates', '.errored..service_locator.FFEicsH.App\\Entity\\Board', NULL, 'Cannot autowire service ".service_locator.FFEicsH": it references class "App\\Entity\\Board" but no such service exists.'],
        ], [
            'board' => 'App\\Entity\\Board',
        ]);
    }
}
