<?php

namespace ContainerLCVAimD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBoardService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FFEicsH.App\Entity\Board' shared service.
     *
     * @return \App\Entity\Board
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FFEicsH": it references class "App\\Entity\\Board" but no such service exists.');
    }
}
