<?php

namespace ContainerLCVAimD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskList2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lUKs57B.App\Entity\TaskList' shared service.
     *
     * @return \App\Entity\TaskList
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lUKs57B": it references class "App\\Entity\\TaskList" but no such service exists.');
    }
}
