<?php

namespace ContainerIDoXiV2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HVyfUojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hVyfUoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hVyfUoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'taskListRepository' => ['privates', 'App\\Repository\\TaskListRepository', 'getTaskListRepositoryService', true],
        ], [
            'taskListRepository' => 'App\\Repository\\TaskListRepository',
        ]);
    }
}
