<?php

namespace ContainerIDoXiV2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YFu3bo_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YFu3bo.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YFu3bo.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'board' => ['privates', '.errored..service_locator.YFu3bo..App\\Entity\\Board', NULL, 'Cannot autowire service ".service_locator.YFu3bo.": it references class "App\\Entity\\Board" but no such service exists.'],
            'boardRepository' => ['privates', 'App\\Repository\\BoardRepository', 'getBoardRepositoryService', true],
        ], [
            'board' => 'App\\Entity\\Board',
            'boardRepository' => 'App\\Repository\\BoardRepository',
        ]);
    }
}
