<?php

namespace ContainerIDoXiV2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LUKs57BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lUKs57B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lUKs57B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'taskList' => ['privates', '.errored..service_locator.lUKs57B.App\\Entity\\TaskList', NULL, 'Cannot autowire service ".service_locator.lUKs57B": it references class "App\\Entity\\TaskList" but no such service exists.'],
        ], [
            'taskList' => 'App\\Entity\\TaskList',
        ]);
    }
}
