<?php

namespace ContainerIDoXiV2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yc9l2iGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Yc9l2iG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Yc9l2iG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'taskList' => ['privates', '.errored..service_locator.Yc9l2iG.App\\Entity\\TaskList', NULL, 'Cannot autowire service ".service_locator.Yc9l2iG": it references class "App\\Entity\\TaskList" but no such service exists.'],
            'taskListRepository' => ['privates', 'App\\Repository\\TaskListRepository', 'getTaskListRepositoryService', true],
        ], [
            'taskList' => 'App\\Entity\\TaskList',
            'taskListRepository' => 'App\\Repository\\TaskListRepository',
        ]);
    }
}
