<?php

namespace ContainerIDoXiV2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TOGM8VGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tOGM8VG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tOGM8VG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'task' => ['privates', '.errored..service_locator.tOGM8VG.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.tOGM8VG": it references class "App\\Entity\\Task" but no such service exists.'],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'task' => 'App\\Entity\\Task',
            'taskRepository' => 'App\\Repository\\TaskRepository',
        ]);
    }
}
