<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBUmjKe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBUmjKe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBUmjKe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBUmjKe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHBUmjKe\App_KernelDevDebugContainer([
    'container.build_hash' => 'HBUmjKe',
    'container.build_id' => '15e2a5f9',
    'container.build_time' => 1677954598,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBUmjKe');
