<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIDoXiV2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIDoXiV2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIDoXiV2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIDoXiV2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIDoXiV2\App_KernelDevDebugContainer([
    'container.build_hash' => 'IDoXiV2',
    'container.build_id' => 'f92723ea',
    'container.build_time' => 1676971168,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIDoXiV2');
