<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOsxYN7M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOsxYN7M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOsxYN7M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOsxYN7M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOsxYN7M\App_KernelDevDebugContainer([
    'container.build_hash' => 'OsxYN7M',
    'container.build_id' => 'b824864e',
    'container.build_time' => 1677968367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOsxYN7M');
